name: semaphore
version: 0.0.1
author: Andrew Mezoni <andrew.mezoni@gmail.com>
description: Semaphore is lightweight data type that is used for controlling access to a common resource inside isolate.
homepage: https://github.com/mezoni/semaphore
dev_dependencies:
  test: any