name: semaphore_plus
version: 0.3.1
description: Semaphore is a lightweight data type that is used for controlling the cooperative access to a common resource inside the isolate.
repository: https://github.com/adrianjagielak/semaphore_plus

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
