name: semaphore
version: 0.1.3
author: Andrew Mezoni <andrew.mezoni@gmail.com>
description: Semaphore is lightweight data type that is used for controlling the cooperative access to a common resource inside the isolate.
homepage: https://github.com/mezoni/semaphore
environment:
  sdk: '>=2.0.0 <3.0.0'
dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.9.1
